#!/usr/bin/env bash

export CONTECO_LABEL="module.ksql_server - ContEco"
export CONTECO_DESCRIPTION="ksql Server module with managed standard URL UI."

export CONTECO_TYPE="module"
export CONTECO_NAME="ksql_server"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
